import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { EvaluationResult } from "@/components/ResultsDashboard";

export function generateReport(result: EvaluationResult) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // ── Title ──
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("SmartGrade — Evaluation Report", pageWidth / 2, y, { align: "center" });
  y += 8;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("AI-Based Automated Answer Evaluation System", pageWidth / 2, y, { align: "center" });
  y += 4;
  doc.setDrawColor(0);
  doc.setLineWidth(0.5);
  doc.line(14, y, pageWidth - 14, y);
  y += 10;

  // ── Summary ──
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 14, y);
  y += 7;

  const summaryData = [
    ["Total Marks", `${result.totalMarksObtained} / ${result.maxMarks}`],
    ["Average Score", `${result.averageScore.toFixed(1)} / ${result.maxAverageScore.toFixed(1)}`],
    ["Grade", result.grade],
    ["Percentage", `${result.percentage}%`],
    ["Questions Attended", `${result.questionsAttended} / ${result.totalQuestions}`],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Metric", "Value"]],
    body: summaryData,
    theme: "grid",
    headStyles: { fillColor: [30, 30, 30], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 10 },
    margin: { left: 14, right: 14 },
  });

  y = (doc as any).lastAutoTable.finalY + 12;

  // ── Part-wise Results ──
  for (const part of result.parts) {
    // Check if we need a new page
    if (y > 240) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(`${part.name}  (${part.markSplit})`, 14, y);
    y += 2;

    const partBody = part.questions.map((q) => [
      `Q${q.questionNumber}`,
      `${q.marksObtained} / ${q.maxMarks}`,
      q.feedback,
    ]);

    autoTable(doc, {
      startY: y,
      head: [["Question", "Marks", "Feedback"]],
      body: partBody,
      theme: "grid",
      headStyles: { fillColor: [30, 30, 30], textColor: 255, fontStyle: "bold" },
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: {
        0: { cellWidth: 25 },
        1: { cellWidth: 25 },
        2: { cellWidth: "auto" },
      },
      margin: { left: 14, right: 14 },
    });

    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // ── Overall Feedback ──
  if (y > 250) {
    doc.addPage();
    y = 20;
  }

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Overall Feedback", 14, y);
  y += 7;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const feedbackLines = doc.splitTextToSize(result.overallFeedback, pageWidth - 28);
  doc.text(feedbackLines, 14, y);
  y += feedbackLines.length * 5 + 10;

  // ── Footer ──
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(130);
    doc.text(
      `Generated by SmartGrade  •  Page ${i} of ${pageCount}  •  ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
    doc.setTextColor(0);
  }

  doc.save("SmartGrade_Report.pdf");
}
